/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tms;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Cuong
 */
public class BuyTicket extends javax.swing.JFrame {
    private Passenger p;
    private Ticket x;
    public static ArrayList<String> used=new ArrayList<>();

    /**
     * Creates new form BuyTicket
     */
    public BuyTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        buyticketname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cccd = new javax.swing.JTextField();
        ten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tuoi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nghe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sotau = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        sotoa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        soghe = new javax.swing.JComboBox<>();
        dangki = new javax.swing.JButton();
        refreshbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(153, 0, 0));

        buyticketname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buyticketname.setForeground(new java.awt.Color(255, 255, 0));
        buyticketname.setText("ĐĂNG KÍ VÉ TÀU");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("CMND/CCCD:");

        cccd.setBackground(new java.awt.Color(255, 255, 255));
        cccd.setForeground(new java.awt.Color(0, 0, 0));
        cccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cccdActionPerformed(evt);
            }
        });
        cccd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cccdKeyTyped(evt);
            }
        });

        ten.setBackground(new java.awt.Color(255, 255, 255));
        ten.setForeground(new java.awt.Color(0, 0, 0));
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Họ và tên: ");

        tuoi.setBackground(new java.awt.Color(255, 255, 255));
        tuoi.setForeground(new java.awt.Color(0, 0, 0));
        tuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuoiActionPerformed(evt);
            }
        });
        tuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuoiKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Tuổi:");

        nghe.setBackground(new java.awt.Color(255, 255, 255));
        nghe.setForeground(new java.awt.Color(0, 0, 0));
        nghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngheActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Nghề Nghiệp:");

        mail.setBackground(new java.awt.Color(255, 255, 255));
        mail.setForeground(new java.awt.Color(0, 0, 0));
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Email:");
        jLabel5.setToolTipText("");

        sdt.setBackground(new java.awt.Color(255, 255, 255));
        sdt.setForeground(new java.awt.Color(0, 0, 0));
        sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Số điện thoại:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Chuyến tàu số:");

        sotau.setBackground(new java.awt.Color(255, 255, 255));
        sotau.setForeground(new java.awt.Color(0, 0, 0));
        sotau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotauActionPerformed(evt);
            }
        });
        sotau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sotauKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Toa:");

        sotoa.setBackground(new java.awt.Color(255, 255, 255));
        sotoa.setForeground(new java.awt.Color(0, 0, 0));
        sotoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoaActionPerformed(evt);
            }
        });
        sotoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sotoaKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Số ghế:");

        soghe.setBackground(new java.awt.Color(255, 255, 255));
        soghe.setForeground(new java.awt.Color(0, 0, 0));
        soghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sogheActionPerformed(evt);
            }
        });

        dangki.setBackground(new java.awt.Color(255, 255, 0));
        dangki.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dangki.setForeground(new java.awt.Color(153, 0, 0));
        dangki.setText("ĐĂNG KÍ");
        dangki.setActionCommand("SignTicket");
        dangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkiActionPerformed(evt);
            }
        });

        refreshbt.setBackground(new java.awt.Color(255, 255, 0));
        refreshbt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        refreshbt.setForeground(new java.awt.Color(153, 0, 0));
        refreshbt.setText("REFRESH");
        refreshbt.setActionCommand("SignTicket");
        refreshbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nghe, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(sotau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sotoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dangki)
                                                .addGroup(panel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(soghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(50, 50, 50)
                                    .addComponent(cccd)))
                            .addComponent(refreshbt)
                            .addComponent(jLabel7)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(buyticketname)))
                .addGap(54, 54, 54))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(buyticketname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sotau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(sotoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(soghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangki)
                    .addComponent(refreshbt))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtActionPerformed
        // TODO add your handling code here:
        addTrainBox();
    }//GEN-LAST:event_refreshbtActionPerformed

    public static void addTrainBox(){
        sotau.removeAllItems();
        for(Trip i:TB.t_list){
            String tmp=i.getTripNumber();
            sotau.addItem(tmp);
        }
    }
    public static void addToaBox(){
        sotoa.removeAllItems();
        for(Trip i:TB.t_list){
            String tmp=String.valueOf(i.getTripNumber());
            if(tmp.equals(sotau.getSelectedItem())){
                for(int j=1;j<=i.getCoachNumber();j++){
                    sotoa.addItem(String.valueOf(j));
                }
            }
        }
    }
    public static void addGheBox(){
        soghe.removeAllItems();
        for(Trip i:TB.t_list){
            String tmp=String.valueOf(i.getTripNumber());
            if(tmp.equals(sotau.getSelectedItem())){
               for(int k=0;k<i.getSeatNumber();k++){
                    soghe.addItem(String.valueOf(k+1));
               }
            }
        }
    }
    private void dangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkiActionPerformed
        // TODO add your handling code here:
        used.add("@#$");
        if(ten.getText().isEmpty()) JOptionPane.showMessageDialog(null,"VUI LÒNG ĐIỀN TÊN","",JOptionPane.ERROR_MESSAGE);
        else if(tuoi.getText().isEmpty()) JOptionPane.showMessageDialog(null,"VUI LÒNG ĐIỀN TUỔI","",JOptionPane.ERROR_MESSAGE);
        else if(sdt.getText().isEmpty()) JOptionPane.showMessageDialog(null,"VUI LÒNG ĐIỀN SỐ ĐIỆN THOẠI","",JOptionPane.ERROR_MESSAGE);
        String o=String.format("%s %s %s",sotau.getSelectedItem().toString(),sotoa.getSelectedItem().toString(),soghe.getSelectedItem().toString());
        if(!used.contains(o)){
            used.add(o);
            p=new Passenger(cccd.getText(),ten.getText(),Integer.parseInt(tuoi.getText()),nghe.getText(),mail.getText(),sdt.getText());
            x=new Ticket(p,sotau.getSelectedItem().toString(),sotoa.getSelectedItem().toString(),soghe.getSelectedItem().toString());         
            x.Promotion(p);
            TB.tk_list.add(x);
            PaymentPage b=new PaymentPage();
            b.info.setText("- MÃ VÉ: "+x.getTicketNumber());
            b.info1.setText("- CMND/CCCD: " + p.getPassport());
            b.info2.setText("- TÊN: " + p.getFullname());
            b.info3.setText("- TUỔI: " + p.getAge());
            b.info4.setText("- NGHỀ NGHIỆP: " + p.getRole());
            b.info5.setText("- EMAIL: " + p.getEmail());
            b.info6.setText("- SỐ ĐIỆN THOẠI: " + p.getTelnumber());
            b.info8.setText("- CHUYẾN TÀU SỐ: "+sotau.getSelectedItem().toString());
            b.info9.setText("- TOA: " + sotoa.getSelectedItem().toString());
            b.info10.setText("- GHẾ: " + soghe.getSelectedItem().toString());
            b.info11.setText("- GIÁ VÉ: "+x.getTicketPrice()+" VND");
            b.setVisible(true);
            this.dispose();
        }
        else if(used.contains(o)){
            JOptionPane.showMessageDialog(null,"CHỖ ĐÃ ĐƯỢC ĐẶT VUI LÒNG CHỌN VỊ TRÍ KHÁC","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dangkiActionPerformed

    private void sogheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sogheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sogheActionPerformed

    private void sotoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotoaActionPerformed
        // TODO add your handling code here:
        addGheBox();
    }//GEN-LAST:event_sotoaActionPerformed

    private void sotauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotauActionPerformed
        // TODO add your handling code here:
        addToaBox();
    }//GEN-LAST:event_sotauActionPerformed

    private void sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void ngheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngheActionPerformed

    private void tuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuoiActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenActionPerformed

    private void cccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cccdActionPerformed

    private void tuoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuoiKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_tuoiKeyTyped

    private void sotauKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sotauKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sotauKeyTyped

    private void sotoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sotoaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_sotoaKeyTyped

    private void cccdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cccdKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_cccdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buyticketname;
    private javax.swing.JTextField cccd;
    private javax.swing.JButton dangki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nghe;
    private java.awt.Panel panel2;
    private javax.swing.JButton refreshbt;
    private javax.swing.JTextField sdt;
    public static javax.swing.JComboBox<String> soghe;
    public static javax.swing.JComboBox<String> sotau;
    public static javax.swing.JComboBox<String> sotoa;
    private javax.swing.JTextField ten;
    private javax.swing.JTextField tuoi;
    // End of variables declaration//GEN-END:variables
}
