/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tms;

import javax.swing.JOptionPane;

/**
 *
 * @author Cuong
 */
public class PaymentPage extends javax.swing.JFrame {


    /**
     * Creates new form PaymentPage
     */
    public PaymentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        thanhtoan = new javax.swing.JButton();
        backbill = new javax.swing.JButton();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        info4 = new javax.swing.JLabel();
        info5 = new javax.swing.JLabel();
        info6 = new javax.swing.JLabel();
        info8 = new javax.swing.JLabel();
        info9 = new javax.swing.JLabel();
        info10 = new javax.swing.JLabel();
        info11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("HÓA ĐƠN ĐẶT VÉ");

        info.setForeground(new java.awt.Color(255, 255, 0));
        info.setText("1");
        info.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info.setPreferredSize(new java.awt.Dimension(300, 300));

        thanhtoan.setBackground(new java.awt.Color(255, 255, 0));
        thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thanhtoan.setForeground(new java.awt.Color(153, 0, 0));
        thanhtoan.setText("THANH TOÁN");
        thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhtoanActionPerformed(evt);
            }
        });

        backbill.setBackground(new java.awt.Color(255, 255, 0));
        backbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbill.setForeground(new java.awt.Color(153, 0, 0));
        backbill.setText("QUAY LẠI");
        backbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbillActionPerformed(evt);
            }
        });

        info1.setForeground(new java.awt.Color(255, 255, 0));
        info1.setText("1");
        info1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info1.setPreferredSize(new java.awt.Dimension(300, 300));

        info2.setForeground(new java.awt.Color(255, 255, 0));
        info2.setText("1");
        info2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info2.setPreferredSize(new java.awt.Dimension(300, 300));

        info3.setForeground(new java.awt.Color(255, 255, 0));
        info3.setText("1");
        info3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info3.setPreferredSize(new java.awt.Dimension(300, 300));

        info4.setForeground(new java.awt.Color(255, 255, 0));
        info4.setText("1");
        info4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info4.setPreferredSize(new java.awt.Dimension(300, 300));

        info5.setForeground(new java.awt.Color(255, 255, 0));
        info5.setText("1");
        info5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info5.setPreferredSize(new java.awt.Dimension(300, 300));

        info6.setForeground(new java.awt.Color(255, 255, 0));
        info6.setText("1");
        info6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info6.setPreferredSize(new java.awt.Dimension(300, 300));

        info8.setForeground(new java.awt.Color(255, 255, 0));
        info8.setText("1");
        info8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info8.setPreferredSize(new java.awt.Dimension(300, 300));

        info9.setForeground(new java.awt.Color(255, 255, 0));
        info9.setText("1");
        info9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info9.setPreferredSize(new java.awt.Dimension(300, 300));

        info10.setForeground(new java.awt.Color(255, 255, 0));
        info10.setText("1");
        info10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info10.setPreferredSize(new java.awt.Dimension(300, 300));

        info11.setForeground(new java.awt.Color(255, 255, 0));
        info11.setText("1");
        info11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info11.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info9, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info10, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(info11, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backbill, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(thanhtoan)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(info9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(info11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbill)
                    .addComponent(thanhtoan))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbillActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new BuyTicket().setVisible(true);
    }//GEN-LAST:event_backbillActionPerformed

    private void thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhtoanActionPerformed
        // TODO add your handling code here:
        String [] tmp=info11.getText().split("\\s+");
        int x=Integer.parseInt(tmp[3]);
        if(x>TB.w.getBalance()) JOptionPane.showMessageDialog(null,"SỐ DƯ TÀI KHOẢN KHÔNG ĐỦ\n VUI LÒNG NẠP THÊM TIỀN","",JOptionPane.ERROR_MESSAGE); 
        else{
            JOptionPane.showMessageDialog(null,"THANH TOÁN THÀNH CÔNG","",JOptionPane.INFORMATION_MESSAGE);
            TB.tk_list.get(TB.tk_list.size()-1).setStatus("ĐÃ THANH TOÁN");
            TB.w.Withdraw(x);
        }
        setVisible(false);
    }//GEN-LAST:event_thanhtoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbill;
    public javax.swing.JLabel info;
    public javax.swing.JLabel info1;
    public javax.swing.JLabel info10;
    public javax.swing.JLabel info11;
    public javax.swing.JLabel info2;
    public javax.swing.JLabel info3;
    public javax.swing.JLabel info4;
    public javax.swing.JLabel info5;
    public javax.swing.JLabel info6;
    public javax.swing.JLabel info8;
    public javax.swing.JLabel info9;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel1;
    private javax.swing.JButton thanhtoan;
    // End of variables declaration//GEN-END:variables
}
