/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tms;

import javax.swing.JLabel;

/**
 *
 * @author Cuong
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        this.setSize(420,420);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        welcometext = new javax.swing.JLabel();
        buttontripinfo = new javax.swing.JButton();
        muave = new javax.swing.JButton();
        tracuu = new javax.swing.JButton();
        sodu = new javax.swing.JButton();

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(153, 0, 0));

        welcometext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcometext.setForeground(new java.awt.Color(255, 255, 0));
        welcometext.setText("CHÀO MỪNG ĐẾN VỚI TAUNHANHVN");

        buttontripinfo.setBackground(new java.awt.Color(255, 255, 255));
        buttontripinfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttontripinfo.setForeground(new java.awt.Color(0, 51, 255));
        buttontripinfo.setText("THÔNG TIN CÁC CHUYẾN");
        buttontripinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontripinfoActionPerformed(evt);
            }
        });

        muave.setBackground(new java.awt.Color(255, 255, 255));
        muave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        muave.setForeground(new java.awt.Color(0, 51, 255));
        muave.setText("ĐĂNG KÍ VÉ TÀU");
        muave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muaveActionPerformed(evt);
            }
        });

        tracuu.setBackground(new java.awt.Color(255, 255, 255));
        tracuu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tracuu.setForeground(new java.awt.Color(0, 51, 255));
        tracuu.setText("TRA CỨU VÉ TÀU");
        tracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracuuActionPerformed(evt);
            }
        });

        sodu.setBackground(new java.awt.Color(255, 255, 255));
        sodu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sodu.setForeground(new java.awt.Color(0, 51, 255));
        sodu.setText("KIỂM TRA SỐ DƯ");
        sodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcometext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttontripinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tracuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(welcometext)
                .addGap(65, 65, 65)
                .addComponent(buttontripinfo)
                .addGap(39, 39, 39)
                .addComponent(muave)
                .addGap(40, 40, 40)
                .addComponent(tracuu)
                .addGap(40, 40, 40)
                .addComponent(sodu)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracuuActionPerformed
        // TODO add your handling code here:
        new TicketInfoFrame().setVisible(true);
    }//GEN-LAST:event_tracuuActionPerformed

    private void muaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muaveActionPerformed
        // TODO add your handling code here:
        new BuyTicket().setVisible(true);
    }//GEN-LAST:event_muaveActionPerformed

    private void buttontripinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontripinfoActionPerformed
        // TODO add your handling code here:
        new TripInfo().setVisible(true);
    }//GEN-LAST:event_buttontripinfoActionPerformed

    private void soduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soduActionPerformed
        // TODO add your handling code here:
        WalletInfo x=new WalletInfo();
        WalletInfo.baosodu.setText("SỐ DƯ HIỆN TẠI: "+TB.w.getBalance()+" VND");
        x.setVisible(true);
    }//GEN-LAST:event_soduActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttontripinfo;
    private javax.swing.JButton muave;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JButton sodu;
    private javax.swing.JButton tracuu;
    private javax.swing.JLabel welcometext;
    // End of variables declaration//GEN-END:variables
}
